### ISSUE TITLE
CTF_JUNCTION_2 final issues

### ISSUE THREAD

**Issue by q3shafe** [q3shafe/trepidation#190]
Just a few missing textures... see screenshots 
![shot0006](https://user-images.githubusercontent.com/933257/53704231-eb3f1e00-3de8-11e9-9b07-2ef6dc861151.jpg)
![shot0007](https://user-images.githubusercontent.com/933257/53704232-eb3f1e00-3de8-11e9-8c4f-d69c84301269.jpg)
![shot0002](https://user-images.githubusercontent.com/933257/53704233-eb3f1e00-3de8-11e9-8f5b-3a9af27daa18.jpg)
![shot0003](https://user-images.githubusercontent.com/933257/53704234-ebd7b480-3de8-11e9-8dc9-b22aede5e9fe.jpg)
![shot0004](https://user-images.githubusercontent.com/933257/53704235-ebd7b480-3de8-11e9-8b79-bcdabed41c26.jpg)
![shot0005](https://user-images.githubusercontent.com/933257/53704237-ebd7b480-3de8-11e9-8038-15fbd294fd23.jpg)

**Comment by q3shafe** [comment]
![shot0009](https://user-images.githubusercontent.com/933257/53704273-4a9d2e00-3de9-11e9-8834-3121f46263ff.jpg)
![shot0010](https://user-images.githubusercontent.com/933257/53704279-58eb4a00-3de9-11e9-8a3e-297860a74680.jpg)
![shot0008](https://user-images.githubusercontent.com/933257/53704280-58eb4a00-3de9-11e9-807d-95a4c0876dc4.jpg)

**Comment by squiciene** [comment]
WOW -  im seeing some MAJOR differences in what you & i have.
here are some pics of what you should have.

![shot0002](https://user-images.githubusercontent.com/33503125/53752391-7b7a7300-3e7c-11e9-8bd9-e041f6c818ad.jpg)
![shot0005](https://user-images.githubusercontent.com/33503125/53752401-87663500-3e7c-11e9-9a82-f780d4a923f9.jpg)
![shot0006](https://user-images.githubusercontent.com/33503125/53752417-8df4ac80-3e7c-11e9-825e-4f0fae700060.jpg)
![shot0008](https://user-images.githubusercontent.com/33503125/53752492-b2508900-3e7c-11e9-896d-e849be9a4f5f.jpg)
the outside lighting is wrong. the color of the metal trim is wrong. 
i dont have time today to send copies, but later on tonight i will send a whole new copy of the map, with scripts,textures & all.

**Comment by squiciene** [comment]
ok, here's what you should need to fix this & the Trepxsus 2 map.    everything is in the appropriate folders, all you need do is replace the existing files with these new ones.  

[base.zip](https://github.com/q3shafe/trepidation/files/2928809/base.zip)

the SCRIPTS folder contains ALL scripts.  i have tinkered with most all of these at some point & i just wanna make sure i have sent you everything up to date.

if all of this works this time..... im thinking of doing a COMPLETE redo of all scripts, &  have a short condensed list, properly organized.   

anyway, i hope this works.

**Comment by q3shafe** [comment]
Ok.. I just added all of those and rebuilt the snapshot.  I also tried to cleanup the scripts folders in both pk3 files, it's still a mess but hopefully not so many dupes.  And damn, I hope I didn't break a bunch of stuff.  I'll pop on it in the morning and have a look at what the snapshot is looking like

**Comment by q3shafe** [comment]
These maps look awesome now!

**Comment by q3shafe** [comment]
Still have this one missing in junction... 
![shot0009](https://user-images.githubusercontent.com/933257/53875359-56981400-3fd2-11e9-9073-d4622574d61a.jpg)

**Comment by squiciene** [comment]
defiantly missing a texture there on the ceiling, but the monitor should be working. that texture has been working since Dystopia 2.   im gonna have to think about this one for a while.  its got to be something on your end.

**Comment by q3shafe** [comment]
Y'know.. I think I may have messed some stuff up when I attempted to
consolidate the scripts, even though I undid the change and rolled it
back, The devastator projectile did not return...

**Comment by angrynerd** [comment]
the new lighting looks great. um i just looked at this now with a relativly new snapshot and the top part is there for me, however the screen is broken still. also the bottom texture below the lava is still missing. the lava its self looks great though. 
![junction2](https://user-images.githubusercontent.com/24483958/54005867-15664800-4129-11e9-8758-df3d00a9c75d.jpg)
![junction1](https://user-images.githubusercontent.com/24483958/54005870-18f9cf00-4129-11e9-8516-91281b9261de.jpg)
in a tad bit of unrelated news but not worthy of adding a new issue for there is one last missing texture on oa_rpg3dm2_s.
![oa1](https://user-images.githubusercontent.com/24483958/54005934-53636c00-4129-11e9-934f-bf08985e737e.jpg)

**Comment by angrynerd** [comment]
to clearify this was a clean install nothing applied but my config; no extra pk3s involved.

**Comment by angrynerd** [comment]
Also in the first screenshot the jump pad does show its texture. this is due to shafes config. to fix this issue you need to set r_vertexLight "0". this issue also ruins some of the monitors that have the graphs (not the main screen). it can also really be seen on trep war ring 2.

**Comment by squiciene** [comment]
here are the missing textures. everything is in the appropriate folders, all you need do is replace the existing files with these new ones.

[textures.zip](https://github.com/q3shafe/trepidation/files/2946719/textures.zip)

all 3 textures shown in the last 3 pics above are included.   the first pic of the lava floor i forgot to send you guys.    the second pic is of the camera texture which i know you already have, & it does work. this could be a script placement issue, or conflicting scripts (copies).  as you can see from the pic of it above that i posted here, it works fine on my end.    the texture for the stairs is also included.

**Comment by squiciene** [comment]
one thing you guys might not have found out yet.  the center of this map is booby trapped.  the monitors that are not functioning on your end yet, allow you to see the center area of the map, & to watch the trap go off.

on the left wall of the monitor room in each base, is a blinking button. if you bump into the button,  the trap goes off & you can watch it in the monitor.

one trap activated from the Blue base (i think) releases grenades across the upper deck around the silo.
the other trap releases rockets that strafe run across the upper deck around the silo.  if you look in the center area, you can see the rocket launcher barrels protruding out of the rock walls surrounding the silo.

**Comment by angrynerd** [comment]
this is a really cool idea there really havent been that many interactive things in trep yet and it seems like a fun inclusion.

**Comment by angrynerd** [comment]
this is a really cool idea there really havent been that many interactive things in trep yet and it seems like a fun inclusion.

**Comment by angrynerd** [comment]
Alright i tested the textures out with a temporary pk3 on my end and they worked so they have been commited. the snapshot for that ofc wont be out untill tomarrow most likely. now other than the monitor there is one last error on that map that i just found. the blue button does not press in correctly. the red one on the other hand works fine. side note i dont know if i just didnt se it or what but i couldnt tell if anything happend when i pushed them. 
![shot0024](https://user-images.githubusercontent.com/24483958/54056302-a1c24a80-41bd-11e9-8cf3-14f50438c89b.jpg)
![shot0025](https://user-images.githubusercontent.com/24483958/54056304-a4bd3b00-41bd-11e9-820c-a6b70b2fb59c.jpg)

**Comment by squiciene** [comment]
good eye!  here is a  new copy of both the map & the .aas file. 
 anytime i have to re-compile a map, i also have to re-make the bot file because the old one wont work anymore.

[junction.zip](https://github.com/q3shafe/trepidation/files/2947700/junction.zip)

as far as the monitor goes,  i am gonna wait until i have the most recent snapshot of the game before i tackle that issue.  but i think you are having a conflict with the COMMON.SHADER file somewhere. not really sure yet.

**Comment by angrynerd** [comment]
Ok i will commit these chamges later tonight omce i have the time to test them.

**Comment by angrynerd** [comment]
Ok i have tested, it does work, and has been commited. side note if it is of any use to you i did here a map specific sound durring the test. i didnt quite here what it said fully but it said something related to junction 2. so whatever that sound was it works.

**Comment by squiciene** [comment]
yes, that was the welcome announcement i told you that i used to test sounds with. the one that was recorded as an 8k .wav file with a 32bitrate float.  i tried to create a new sound file that mimicked his, but without success.   all i got was static playback.  ...even when i upped it to 22k.
it says, "watch your step as you stroll along the junction station".    i wonder if thats Gigons voice.

**Comment by angrynerd** [comment]
I dont know how in in the hell he did it but. @q3shafe 
![shot0034](https://user-images.githubusercontent.com/24483958/54477498-d8601c80-47de-11e9-8b8b-b2eb5356a9a2.jpg)
![shot0035](https://user-images.githubusercontent.com/24483958/54477499-d8f8b300-47de-11e9-9516-487767b7eeed.jpg)
![shot0036](https://user-images.githubusercontent.com/24483958/54477500-d8f8b300-47de-11e9-97c7-097dde15f3be.jpg)
![shot0037](https://user-images.githubusercontent.com/24483958/54477502-d8f8b300-47de-11e9-94d6-32ddbe2003a2.jpg)
![shot0038](https://user-images.githubusercontent.com/24483958/54477504-da29e000-47de-11e9-87fc-df58c44631b8.jpg)
![shot0039](https://user-images.githubusercontent.com/24483958/54477505-dac27680-47de-11e9-9607-db27a452edcb.jpg)
also nice texture with the accents there @squiciene ;).

**Comment by angrynerd** [comment]
i tried to overlay my test pk3 which had fixes for some of this stuff and it didnt even matter.

**Comment by angrynerd** [comment]
actually i will admit one of the pictures was properly fixed by the test pk3 that being the blue button. i know for a fact that i commited that change though... for referense this is the test pk3 it had had all of the changes before last snapshot essentially. 
[zzzztextures.zip](https://github.com/q3shafe/trepidation/files/2974049/zzzztextures.zip)

**Comment by angrynerd** [comment]
I didnt screenshot again but the lava and stair textures also mentiuon up further are also still broke. did any of my changes even get put into the snapshot wtf.

**Comment by angrynerd** [comment]
i can see that the changes are in their and this is the latest snapshot as of 20 minutes ago. i can see that stuff is actually broken with this map because of that but the cvhanges that i made prior just dont seem to exist and i dont understand.

**Comment by angrynerd** [comment]
yeah they arent there none of may changes are in the snapshot pk3 i just looked. at the very least the textures because some of the .bsp and .aas were overwrites.

**Comment by squiciene** [comment]
did this issue get fixed?

**Comment by angrynerd** [comment]
I thought it was fixed but the things that i have commited dont seem to exist ad with the changes within the last few commits has broken most of it again.

**Comment by angrynerd** [comment]
@q3shafe why does it seem that none of my commits are actually in the snapshot

**Comment by squiciene** [comment]
this is definately a texture placement problem.  i have just installed the latest dev snapshot, & tested it.
the shader files are good where you have them & they all work.   
the monitors in both dystopia 2 & junction 2, & the other textures that are missing on Junction 2 are missing because the textures i sent you were either not placed in the correct directory, or you have a .cfg file somewhere that has incorrect file location directories listed within it.

the missing textures you cant see are located in the following folders;
textures/common    &  textures/oa_bases  &   textures/details

in textures/common the following images should be present
camera_veiw.jpg    here is a copy
![camera_veiw](https://user-images.githubusercontent.com/33503125/54482377-082c1600-4819-11e9-8994-20e53089ab4c.jpg)

in textures/oa_bases the following images should be present

![crete_black](https://user-images.githubusercontent.com/33503125/54482390-432e4980-4819-11e9-937a-b6f38bf8faa2.jpg)
![crete_blue](https://user-images.githubusercontent.com/33503125/54482391-432e4980-4819-11e9-9105-ce8957340e31.jpg)
![crete_green](https://user-images.githubusercontent.com/33503125/54482392-432e4980-4819-11e9-83bb-5dded410d464.jpg)
![crete_red](https://user-images.githubusercontent.com/33503125/54482394-49bcc100-4819-11e9-9dc5-a676e4e9ac91.jpg)
![crete_white](https://user-images.githubusercontent.com/33503125/54482395-49bcc100-4819-11e9-81d0-aca26545795b.jpg)
![crete_yellow](https://user-images.githubusercontent.com/33503125/54482396-49bcc100-4819-11e9-9167-3400a4e81dd7.jpg)
![crete_lt_blue](https://user-images.githubusercontent.com/33503125/54482397-49bcc100-4819-11e9-98f6-bf70f0d16d84.jpg)
![crete_orange](https://user-images.githubusercontent.com/33503125/54482398-4a555780-4819-11e9-8d71-7cdc103287a5.jpg)
![crete_purp](https://user-images.githubusercontent.com/33503125/54482399-4a555780-4819-11e9-9582-ce5a29848b04.jpg)

in textures/details the following images should be present


![copperpipe2](https://user-images.githubusercontent.com/33503125/54482416-812b6d80-4819-11e9-94a4-00b1f8cf2f84.jpg)
![copperpipe](https://user-images.githubusercontent.com/33503125/54482419-838dc780-4819-11e9-957e-036815c2fd8c.jpg)
![btdt](https://user-images.githubusercontent.com/33503125/54482422-8983a880-4819-11e9-9136-25049f80de34.jpg)
![rtdt](https://user-images.githubusercontent.com/33503125/54482424-956f6a80-4819-11e9-8984-835cae1c5dc4.jpg)
![tb](https://user-images.githubusercontent.com/33503125/54482425-96080100-4819-11e9-862d-442144ff984b.jpg)
![d_conc](https://user-images.githubusercontent.com/33503125/54482428-9f916900-4819-11e9-8077-ee21e5debb11.jpg)
![floorstone1b](https://user-images.githubusercontent.com/33503125/54482429-9f916900-4819-11e9-8c9e-4a50e30e46df.jpg)


i threw a few extras in there to be sure you are upto date

**Comment by angrynerd** [comment]
Last snapshot before this i thought the monitors on dystopia worked?

**Comment by squiciene** [comment]
the new snapshot i just downloaded tonight showed the monitors not working..

**Comment by q3shafe** [comment]
Last nights snapshot also had non-working monitors

**Comment by squiciene** [comment]
ok.... i think the ctf_junction_2 issue should be closed, as the only remaining issue here is the monitor.
a new issue covering the monitor issue should be opened titled , "misc_portal" should be opened, as that is what this issue is all about.  i will start digging around in the new snapshot & see if i can find the problem.
